title: annM01's blog
author: annM01
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All about the SF Giants and Golden State Warriors 

# social links
twitter_username: your-twitter-handle
github_username:  annM01

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
